=== Arzdaksa/arzsGuessMarket/engine/xml_files_dir/GM-EX1-Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Guess-Market">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GM-events"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GM-events">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GM-event" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GM-event">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id"/>
                <xs:element ref="description"/>
                <xs:element ref="commission"/>
                <xs:element ref="GM-options"/>
                <xs:element ref="GM-method"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="id" type="xs:int"/>

    <xs:element name="description" type="xs:string"/>

    <xs:element name="commission">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:int">
                    <xs:attribute name="type" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="on-close"/>
                                <xs:enumeration value="on-purchase"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="GM-options">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GM-option" minOccurs="2" maxOccurs="2"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GM-option" type="xs:string"/>

    <xs:element name="GM-method">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="GM-LMSR"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="GM-LMSR">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="b"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="b" type="xs:int"/>

</xs:schema>

=== Arzdaksa/arzsGuessMarket/engine/xml_files_dir/miltyXmlFile.xml
<Guess-Market xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GM-EX1-schema.xsd">
    <GM-events>
        <GM-event name="Mujtaba is Dead">
            <id>1</id>
            <description>This event gambles if Mujtaba is a live or not. it will be determined if he will be shown in public until 31.8.26</description>
            <comision type="on-purchase">5</comision>
            <GM-options>
                <GM-option>Hell Yea !</GM-option>
                <GM-option>No way !</GM-option>
            </GM-options>
            <GM-method>
                <GM-LMSR>
                    <b>100</b>
                </GM-LMSR>
            </GM-method>
        </GM-event>
        <GM-event name="World Cap Winner">
            <id>2</id>
            <description>Who do you think will win the world cap ?</description>
            <comision type="on-close">15</comision>
            <GM-options>
                <GM-option>Argentina</GM-option>
                <GM-option>Spain</GM-option>
            </GM-options>
            <GM-method>
                <GM-LMSR>
                    <b>50</b>
                </GM-LMSR>
            </GM-method>
        </GM-event>
        <GM-event name="Earth Quake on Dead Sea">
            <id>3</id>
            <description>Will there be an earth quake on the dead sea until the December 31th 2026</description>
            <comision type="on-purchase">50</comision>
            <GM-options>
                <GM-option>Yes</GM-option>
                <GM-option>No</GM-option>

            </GM-options>
            <GM-method>
                <GM-LMSR>
                    <b>400</b>
                </GM-LMSR>
            </GM-method>
        </GM-event>
    </GM-events>
</Guess-Market>
